
main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Blog
    url: '#posts'
    weight: 60
  - name: Projects
    url: '#projects'
    weight: 20
  - name: Talks
    url: '#talks'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 50